/*
 * File: app/view/personas/PanelPrincipalViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PrototipoWeb.view.personas.PanelPrincipalViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.personaspanelprincipal',

    requires: [
        'PrototipoWeb.view.override.personas.PanelPrincipalViewController'
    ],

    control: {
        "button": {
            click: 'onButtonClick'
        }
    },

    onButtonClick: function(button, e, eOpts) {

    },

    onBtnMongoNodejsClick: function(button, e, eOpts) {

    },

    onBtnMongoWebAPIClick: function(button, e, eOpts) {

    },

    onBtnOracleNodejsClick: function(button, e, eOpts) {

    },

    onBtnOracleWebAPIClick: function(button, e, eOpts) {

    },

    onBtnCacheDatosClick: function(button, e, eOpts) {

    },

    onBtnCacheDatosDefinicionClick: function(button, e, eOpts) {

    },

    onTabpanelTabChange: function(tabPanel, newCard, oldCard, eOpts) {

    },

    onViewportBeforeRender: function(component, eOpts) {

    }

});
