/*
 * File: app/view/personas/PanelPrincipal.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PrototipoWeb.view.personas.PanelPrincipal', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.panelprincipal',

    requires: [
        'PrototipoWeb.view.personas.PanelPrincipalViewModel',
        'PrototipoWeb.view.personas.PanelPrincipalViewController',
        'Ext.toolbar.Toolbar',
        'Ext.container.ButtonGroup',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.Label'
    ],

    controller: 'personaspanelprincipal',
    viewModel: {
        type: 'personaspanelprincipal'
    },
    style: 'background-color: #FFFFFF;',
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            flex: 0,
            region: 'north',
            itemId: 'pnlHeader',
            collapsed: true,
            collapsible: true,
            glyph: 'xf0c1@FontAwesome',
            title: 'Cambio de Conexiones',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    itemId: 'tlbUrls',
                    items: [
                        {
                            xtype: 'buttongroup',
                            frame: false,
                            title: 'MongoDB',
                            columns: 2,
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnMongoNodejs',
                                    glyph: 'xf0c1@FontAwesome',
                                    text: 'Urls Node.js',
                                    listeners: {
                                        click: 'onBtnMongoNodejsClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnMongoWebAPI',
                                    glyph: 'xf0c1@FontAwesome',
                                    text: 'Urls Web API',
                                    listeners: {
                                        click: 'onBtnMongoWebAPIClick'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'buttongroup',
                            frame: false,
                            title: 'Oracle',
                            columns: 2,
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnOracleNodejs',
                                    glyph: 'xf0c1@FontAwesome',
                                    text: 'Urls Node.js',
                                    listeners: {
                                        click: 'onBtnOracleNodejsClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnOracleWebAPI',
                                    glyph: 'xf0c1@FontAwesome',
                                    text: 'Urls Web API',
                                    listeners: {
                                        click: 'onBtnOracleWebAPIClick'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'buttongroup',
                            frame: false,
                            title: 'Local',
                            columns: 2,
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'btnCacheDatos',
                                    glyph: 'xf0c1@FontAwesome',
                                    text: 'Cache de Datos',
                                    listeners: {
                                        click: 'onBtnCacheDatosClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'btnCacheDatosDefinicion',
                                    glyph: 'xf0c1@FontAwesome',
                                    text: 'API Documentation',
                                    listeners: {
                                        click: 'onBtnCacheDatosDefinicionClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'tabpanel',
            region: 'center',
            reference: 'tabOpciones',
            margin: '10 10 10 10',
            items: [
                {
                    xtype: 'panel',
                    cls: 'bordeTab',
                    itemId: 'tab2',
                    layout: 'border',
                    title: '<i class="fa fa-cog fa-spin fa-lg"></i> Prototipo Web Basico - Dinamico',
                    items: [
                        {
                            xtype: 'container',
                            flex: 0,
                            region: 'north',
                            height: 76,
                            style: 'background-color: #e6e6e6',
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'label',
                                    flex: 0,
                                    cls: [
                                        'mensaje',
                                        'animated fadeIn',
                                        'delayAnimation'
                                    ],
                                    html: '<i class="fa fa-tag fa-2x"></i> Para dar de alta un nuevo elemento seleccione el botón <span class="aviso">Nuevo registro</span> y para borrar un elemento seleccione <span class="aviso">Borrar registro</span>.'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            region: 'center',
                            reference: 'pnlDinamico',
                            itemId: 'pnlDinamico',
                            layout: 'fit',
                            glyph: 'xf0c0@FontAwesome',
                            title: 'Personas Registradas'
                        }
                    ]
                }
            ],
            listeners: {
                tabchange: 'onTabpanelTabChange'
            }
        }
    ],
    listeners: {
        beforerender: 'onViewportBeforeRender'
    }

});