/*
 * File: app/view/personas/wVentanaCapturaPersona.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PrototipoWeb.view.personas.wVentanaCapturaPersona', {
    extend: 'Ext.window.Window',
    alias: 'widget.personaswventanacapturapersona',

    requires: [
        'PrototipoWeb.view.personas.wVentanaCapturaPersonaViewModel',
        'PrototipoWeb.view.personas.wVentanaCapturaPersonaViewController',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    controller: 'personaswventanacapturapersona',
    viewModel: {
        type: 'personaswventanacapturapersona'
    },
    cls: 'animated fadeIn',
    height: 768,
    width: 650,
    layout: 'fit',
    glyph: 'xf234@FontAwesome',
    modal: true,

    items: [
        {
            xtype: 'form',
            reference: 'frmModificacionDatos',
            itemId: 'frmModificacionDatos',
            ui: 'light',
            defaults: {
                padding: 10
            },
            collapsible: false,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    reference: 'cntCol1',
                    itemId: 'column1',
                    scrollable: 'true',
                    layout: 'anchor'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    reference: 'cntCol2',
                    itemId: 'column2',
                    scrollable: 'true',
                    layout: 'anchor'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    itemId: 'tlbOpciones',
                    ui: 'untitled-ui-1',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    bind: {
                        hidden: '{desapareceToolbar}'
                    },
                    items: [
                        {
                            xtype: 'button',
                            formBind: true,
                            reference: 'btnAceptar',
                            disabled: true,
                            itemId: 'btnAceptar',
                            glyph: 'xf058@FontAwesome',
                            text: 'Aceptar',
                            listeners: {
                                click: 'onBtnAceptarClick'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnCancelar',
                            glyph: 'xf00d@FontAwesome',
                            text: 'Cancelar',
                            listeners: {
                                click: 'onBtnCancelarClick'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onWindowAfterRender',
        beforerender: 'onWindowBeforeRender'
    }

});