/*
 * File: app/view/personas/wVentanaCapturaPersonaViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PrototipoWeb.view.personas.wVentanaCapturaPersonaViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.personaswventanacapturapersona',

    requires: [
        'PrototipoWeb.view.override.personas.wVentanaCapturaPersonaViewController'
    ],

    control: {
        "textfield": {
            specialkey: 'onTextfieldSpecialkey'
        }
    },

    onTextfieldSpecialkey: function(field, e, eOpts) {

    },

    onBtnAceptarClick: function(button, e, eOpts) {

    },

    onBtnCancelarClick: function(button, e, eOpts) {

    },

    onWindowAfterRender: function(component, eOpts) {

    },

    onWindowBeforeRender: function(component, eOpts) {

    }

});
